### PR TITLE
Logo with solid background

### PR DESCRIPTION
**Pull request by jweisman**
Hi there. Suggesting this version of the app's icon with a solid background, as suggested by https://developers.exlibrisgroup.com/cloudapps/docs/manifest/. This provides consistency in the app list. 

Thanks!

### CODE REVIEW

**Comment by kthbiblioteket** [comment]
Hi Josh!

I didn't exactly understand the comment about a solid background. The icon has the solid white background that we prefer at the moment. You mean that the icons should have another color than white? (where does that "red" color come from?)

/Thomas

**Comment by jweisman** [comment]
Hi- thanks for your question. Yes, we do ask for a solid color background in order to provide a consistent look in the Cloud App center, as seen below. You're welcome to select a different color for the background if you prefer.

Screen Shot 2021-03-01 at 18 53 10

**Comment by thompa21** [comment]
Hi

Ah I see! Then we will fix this :)

/Thomas

**Comment by thompa21** [comment]
Logo changed to solid blue background

**Comment by jweisman** [comment]
Great- thanks!

**Pull request closed without merging**
